import type { VercelRequest, VercelResponse } from '@vercel/node';
import { readFileSync } from 'fs';
import { join } from 'path';

export default function handler(req: VercelRequest, res: VercelResponse) {
  try {
    const postsPath = join(process.cwd(), 'blog', 'posts.json');
    const posts = JSON.parse(readFileSync(postsPath, 'utf-8'));
    const citiesPath = join(process.cwd(), 'cities.json');
    const cities = JSON.parse(readFileSync(citiesPath, 'utf-8'));
    // Generated by scripts/build-transload-pages.js — 240 region/city pages that
    // make the 2,469-facility transload dataset crawlable. Before this, the whole
    // directory was one URL loading its data client-side, so none of it could rank.
    // Wrapped: a missing manifest must degrade to "no transload URLs", never a
    // 500 that takes the entire sitemap down.
    let transloadPages: Array<{ loc: string; priority: string }> = [];
    try {
      const p = join(process.cwd(), 'transload', 'pages.json');
      transloadPages = JSON.parse(readFileSync(p, 'utf-8')).pages || [];
    } catch {
      console.warn('sitemap: transload/pages.json missing — run scripts/build-transload-pages.js');
    }
    // Commodity + rail-hub pages (crawlable layer for the commodity-flow map).
    // Same degrade-to-empty contract as the transload manifest.
    let commodityPages: Array<{ loc: string; priority: string }> = [];
    try {
      const cp = join(process.cwd(), 'commodities', 'pages.json');
      commodityPages = JSON.parse(readFileSync(cp, 'utf-8')).pages || [];
    } catch {
      console.warn('sitemap: commodities/pages.json missing — run scripts/build-commodity-pages.js');
    }
    // Rail-served WAREHOUSE pages. Separate from /transload/ on purpose: GSC shows
    // 40 warehouse-intent queries with 200 impressions and zero clicks, ranking
    // 11-87, because nothing targets them. Same degrade-to-empty contract.
    let warehousePages: Array<{ loc: string; priority: string }> = [];
    try {
      const wp = join(process.cwd(), 'rail-served-warehouses', 'pages.json');
      warehousePages = JSON.parse(readFileSync(wp, 'utf-8')).pages || [];
    } catch {
      console.warn('sitemap: rail-served-warehouses/pages.json missing — run scripts/build-warehouse-pages.js');
    }
    // Rail-served business pages (crawlable layer for the confidence-tiered
    // rail-served dataset). Same degrade-to-empty contract as the manifests above.
    let railServedPages: Array<{ loc: string; priority: string }> = [];
    try {
      const rp = join(process.cwd(), 'rail-served', 'pages.json');
      railServedPages = JSON.parse(readFileSync(rp, 'utf-8')).pages || [];
    } catch {
      console.warn('sitemap: rail-served/pages.json missing — run scripts/build-railserved-pages.js');
    }
    // NOTE: the ~359 programmatic /rates lane pages are intentionally EXCLUDED
    // from the sitemap (2026-06-01). GSC showed 27 impressions / 0 clicks across
    // all of them over 90d — no search demand — and they were diluting the
    // domain's quality signal. They're also noindex'd via X-Robots-Tag in
    // vercel.json. Real cost-related search demand is served by the blog + the
    // rate-quote tool instead.
    const today = new Date().toISOString().split("T")[0];

    const staticPages = [
      { loc: "/", priority: "1.0", changefreq: "weekly" },
      { loc: "/services", priority: "0.9", changefreq: "monthly" },
      { loc: "/outsourced-rail-department", priority: "0.9", changefreq: "monthly" },
      { loc: "/rail-transload-services", priority: "0.9", changefreq: "monthly" },
      { loc: "/contact", priority: "0.8", changefreq: "monthly" },
      { loc: "/blog", priority: "0.9", changefreq: "daily" },
      { loc: "/courses", priority: "0.9", changefreq: "weekly" },
      { loc: "/rail-freight", priority: "0.8", changefreq: "weekly" },
      { loc: "/tools", priority: "0.9", changefreq: "weekly" },
      { loc: "/tools/rail-rate-quote", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/transload-directory", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/demurrage-calculator", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/railcar-selector", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/railcar-capacity", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/stcc-finder", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/rail-bol-builder", priority: "0.8", changefreq: "monthly" },
      // Added 2026-07-22. These six shipped but were never added here, so
      // they had no crawl path from the sitemap — 9 of 11 tools had zero GSC
      // impressions over 90 days. Tool pages convert impressions to clicks at
      // ~2x the position benchmark (vs ~0.16x for informational blog posts),
      // so visibility here is the binding constraint, not page quality.
      { loc: "/tools/rail-vs-truck", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/rail-fleet-calculator", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/rail-served-businesses", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/commodity-flow-map", priority: "0.8", changefreq: "monthly" },
      { loc: "/tools/sublease-board", priority: "0.8", changefreq: "weekly" },
      // Regenerated from data/fsc/current.json on the 1st of each month, so
      // changefreq is monthly and genuinely accurate.
      { loc: "/tools/rail-fuel-surcharge", priority: "0.9", changefreq: "monthly" },
      { loc: "/tools/rail-transit-time", priority: "0.9", changefreq: "weekly" },
      // Added 2026-07-23. Static content/SEO page — figures refreshed from
      // published sources (GATX LPI, Commtrex, Grain Journal, AAR) as they update.
      { loc: "/tools/railcar-lease-rates", priority: "0.8", changefreq: "monthly" },
      { loc: "/privacy-policy", priority: "0.3", changefreq: "yearly" },
      { loc: "/terms-of-service", priority: "0.3", changefreq: "yearly" },
    ];

    const coursePages = [
      "rail-freight-fundamentals", "working-with-railroads", "railroad-pricing",
      "demurrage", "transloading", "surviving-psr", "bulk-commodity-deep-dives",
      "safety-compliance-regulations", "technology-future-of-rail", "building-your-rail-strategy",
    ];

    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

    for (const page of staticPages) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com${page.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${page.changefreq}</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
    }

    for (const slug of coursePages) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com/courses/${slug}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.6</priority>\n  </url>\n`;
    }

    for (const post of posts) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com/blog/${post.slug}</loc>\n    <lastmod>${post.date}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>\n`;
    }

    for (const city of cities) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com/rail-freight/${city.slug}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.6</priority>\n  </url>\n`;
    }

    for (const page of transloadPages) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com${page.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
    }

    for (const page of railServedPages) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com${page.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
    }

    for (const page of warehousePages) {
      xml += `  <url>\n    <loc>https://steelwheellogistics.com${page.loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
    }

    for (const page of commodityPages) {
      // commodities/pages.json stores absolute URLs; tolerate either form.
      const loc = page.loc.startsWith('http')
        ? page.loc
        : `https://steelwheellogistics.com${page.loc}`;
      xml += `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>${page.priority}</priority>\n  </url>\n`;
    }

    xml += `</urlset>`;

    res.setHeader("Content-Type", "application/xml; charset=utf-8");
    res.setHeader("Cache-Control", "public, max-age=3600");
    return res.status(200).send(xml);
  } catch (err) {
    console.error("Sitemap generation error:", err);
    return res.status(500).send("Sitemap generation failed");
  }
}
